// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/generate": {
            "post": {
                "description": "Manually generate summaries and grades for all uploads",
                "produces": [
                    "application/json"
                ],
                "summary": "Generate summaries",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/summaries": {
            "get": {
                "description": "Returns all employees with summaries and grades",
                "produces": [
                    "application/json"
                ],
                "summary": "Get all summaries",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/summaries/{employee}": {
            "get": {
                "description": "Get summary and grade for a specific employee",
                "produces": [
                    "application/json"
                ],
                "summary": "Get employee summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee name",
                        "name": "employee",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "Upload an employee's report file",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain"
                ],
                "summary": "Upload a report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee name",
                        "name": "employee",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Report file",
                        "name": "summary",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File uploaded",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "deonna-maximal-kyleigh.ngrok-free.dev",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Employee Summary & Grading API",
	Description:      "Upload employee reports, generate summaries, and see grades.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
